# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'eleven.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 400)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_show = QtWidgets.QFrame(self.centralwidget)
        self.frame_show.setGeometry(QtCore.QRect(80, 40, 200, 200))
        self.frame_show.setStyleSheet("border-image: url(:/icons/icons/Onur_Karaguler.png);")
        self.frame_show.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_show.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_show.setObjectName("frame_show")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 21))
        self.menubar.setObjectName("menubar")
        self.menuRenkler = QtWidgets.QMenu(self.menubar)
        self.menuRenkler.setObjectName("menuRenkler")
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setIconSize(QtCore.QSize(36, 36))
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.statusBar.setFont(font)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.action_blue = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_blue.setIcon(icon)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.action_blue.setFont(font)
        self.action_blue.setObjectName("action_blue")
        self.action_red = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/Oyun_1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_red.setIcon(icon1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.action_red.setFont(font)
        self.action_red.setObjectName("action_red")
        self.action_green = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/4.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_green.setIcon(icon2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.action_green.setFont(font)
        self.action_green.setObjectName("action_green")
        self.action_yellow = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/7.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_yellow.setIcon(icon3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.action_yellow.setFont(font)
        self.action_yellow.setObjectName("action_yellow")
        self.action_black_white = QtWidgets.QAction(MainWindow)
        self.action_black_white.setCheckable(True)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_black_white.setIcon(icon4)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.action_black_white.setFont(font)
        self.action_black_white.setObjectName("action_black_white")
        self.menuRenkler.addAction(self.action_blue)
        self.menuRenkler.addSeparator()
        self.menuRenkler.addAction(self.action_red)
        self.menuRenkler.addAction(self.action_green)
        self.menubar.addAction(self.menuRenkler.menuAction())
        self.toolBar.addAction(self.action_blue)
        self.toolBar.addAction(self.action_red)
        self.toolBar.addAction(self.action_green)
        self.toolBar.addAction(self.action_yellow)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_black_white)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ders=11"))
        self.menuRenkler.setTitle(_translate("MainWindow", "Renkler"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.action_blue.setText(_translate("MainWindow", "Mavi"))
        self.action_blue.setToolTip(_translate("MainWindow", "Mavi kuşu seç"))
        self.action_blue.setShortcut(_translate("MainWindow", "Shift+B"))
        self.action_red.setText(_translate("MainWindow", "Kırmızı"))
        self.action_red.setToolTip(_translate("MainWindow", "Kırmızı kuşu seç"))
        self.action_green.setText(_translate("MainWindow", "Yeşil"))
        self.action_green.setToolTip(_translate("MainWindow", "Yeşil kuşu seç"))
        self.action_green.setShortcut(_translate("MainWindow", "Shift+G"))
        self.action_yellow.setText(_translate("MainWindow", "Sarı"))
        self.action_yellow.setToolTip(_translate("MainWindow", "Sarı kuşu seç"))
        self.action_yellow.setShortcut(_translate("MainWindow", "Shift+Y"))
        self.action_black_white.setText(_translate("MainWindow", "Siyah"))
        self.action_black_white.setToolTip(_translate("MainWindow", "Siyah kuşu seç"))
        self.action_black_white.setShortcut(_translate("MainWindow", "Shift+K"))
import icons


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
